version: '2'
services:
  labmanager:
    image: gigantum/labmanager-dev:latest
    entrypoint: /usr/local/bin/entrypoint.sh
    command: /bin/bash
    ports:
     - "10000:10000"
     - "10001:10001"
     - "10002:10002"
    volumes:
    - /Users/dean/gigantum:/mnt/gigantum:cached
    - /var/run/docker.sock:/var/run/docker.sock
    - labmanager_share_vol:/mnt/share
    environment:
     - LOCAL_USER_ID=501
     - HOST_WORK_DIR=/Users/dean/gigantum
    network_mode: "bridge"

volumes:
  labmanager_share_vol:
    external: true
