codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      core:
        paths:
        - packages/gtmcore/*
      api:
        paths:
        - packages/gtmapi/*
    patch:
      core:
        paths:
        - packages/gtmcore/*
      api:
        paths:
        - packages/gtmapi/*
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
