auth:
  audience: api.gigantum.io
  client_id: 0Ajo8Ov6Qriafo0xVpSyejWy1pwNWdhk
  identity_manager: local
  provider_domain: gigantum.auth0.com
  signing_algorithm: RS256
build_info:
  application: LabManager
  built_on: '2018-09-11 22:03:15.041291'
  revision: 8a7ae4d7cde4e76ffcac9336d05ddf20a30bb20a
container:
  cpu: null
  cuda_version: null
  memory: null
core:
  import_demo_on_first_login: true
  logging_config: /etc/gigantum/logging.json
  team_mode: false
detaildb:
  logfile_limit: 8000000
  options:
    compress: true
    compress_min_bytes: 4000
environment:
  repo_url:
  - https://github.com/gigantum/environment-components.git
flask:
  DEBUG: false
  TESTING: false
  allow_cors: true
from: null
git:
  backend: filesystem-shim
  default_remote: repo.gigantum.io
  lfs_enabled: true
  remotes:
    repo.gigantum.io:
      admin_service: usersrv.gigantum.io
      index_service: api.gigantum.com/read
      remote_type: gitlab
  working_directory: /mnt/gigantum
lock:
  auto_renewal: false
  expire: null
  redis:
    db: 3
    host: localhost
    port: 6379
    strict: true
  reset_on_start: true
  timeout: 120
proxy:
  api_host: localhost
  api_port: 1999
  apparent_proxy_port: 10000
  external_proxy_port: 10000
  labmanager_api_prefix: /api
