auth:
  audience: api.gigantum.io
  client_id: 0Ajo8Ov6Qriafo0xVpSyejWy1pwNWdhk
  identity_manager: browser
  provider_domain: gigantum.auth0.com
  signing_algorithm: RS256
build_info:
  application: LabManager
  built_on: '2018-09-07 20:17:52.667274'
  revision: e38a62e55f69a41994a3611e48146a4ee4f0a7b6
container:
  cpu: 2
  cuda_version: null
  memory: 8g
core:
  import_demo_on_first_login: true
  logging_config: /etc/gigantum/logging.json
  team_mode: false
detaildb:
  logfile_limit: 8000000
  options:
    compress: true
    compress_min_bytes: 4000
environment:
  repo_url:
  - https://github.com/gigantum/environment-components.git
flask:
  DEBUG: false
  TESTING: false
  allow_cors: true
from: null
git:
  backend: filesystem-shim
  default_remote: repo.gigantum.io
  lfs_enabled: true
  remotes:
    repo.gigantum.io:
      admin_service: usersrv.gigantum.io
      index_service: api.gigantum.com/read/index
      remote_type: gitlab
  working_directory: /mnt/gigantum
lock:
  auto_renewal: false
  expire: null
  redis:
    db: 3
    host: localhost
    port: 6379
    strict: true
  reset_on_start: true
  timeout: 120
proxy:
  api_host: localhost
  api_port: 1999
  apparent_proxy_port: 80
  external_proxy_port: 10000
  labmanager_api_prefix: /api
